# Generated by Django 5.0.2 on 2024-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('population', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('top_attractions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
