# Generated by Django 5.0.2 on 2024-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0003_city_latitude_city_longitude_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sumamary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
