# Generated by Django 5.0.2 on 2024-02-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0004_city_sumamary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='sumamary',
            new_name='summary',
        ),
    ]
